import { Icon } from '@iconify/react';

export const APP_ICONS = {
  home: 'solar:home-2-linear',
  projects: 'solar:widget-4-linear',
  edit: 'solar:pen-2-linear',
  data: 'solar:database-linear',
  models: 'solar:box-linear',
  reports: 'solar:chart-square-linear',
  media: 'solar:gallery-linear',
  settings: 'solar:settings-linear',
  collapse: 'solar:alt-arrow-down-linear',
  expand: 'solar:alt-arrow-up-linear',
  search: 'solar:magnifer-linear',
  plus: 'solar:add-circle-linear',
  page: 'solar:documents-linear',
  layer: 'solar:layers-linear',
  visible: 'solar:eye-linear',
  hidden: 'solar:eye-closed-linear',
  lock: 'solar:lock-password-linear',
  unlock: 'solar:lock-keyhole-unlocked-linear',
  group: 'solar:widget-add-linear',
  ungroup: 'solar:widget-4-bold-duotone',
  select: 'solar:cursor-linear',
  wire: 'solar:share-linear',
  delete: 'solar:trash-bin-trash-linear',
  play: 'solar:play-bold-duotone',
  pause: 'solar:pause-bold-duotone',
  calculate: 'solar:flash-line-duotone',
  save: 'solar:diskette-linear',
  folder: 'solar:folder-open-linear',
  json: 'solar:code-linear',
  png: 'solar:gallery-linear',
  svg: 'solar:figma-linear',
  layout: 'solar:slider-horizontal-linear',
  clear: 'solar:eraser-linear',
  zoomIn: 'solar:magnifer-zoom-in-linear',
  zoomOut: 'solar:magnifer-zoom-out-linear',
  fit: 'solar:maximize-square-2-linear',
  grid: 'solar:grid-linear',
  snap: 'solar:magnet-linear',
  ortho: 'solar:ruler-linear',
  live: 'solar:playback-speed-linear',
  wiki: 'simple-icons:wikipedia',
  back: 'solar:arrow-left-linear',
  themeLight: 'solar:sun-2-linear',
  themeDark: 'solar:moon-linear',
  user: 'solar:user-circle-linear',
  down: 'solar:alt-arrow-down-linear',
  module: 'solar:cpu-linear',
  preset: 'solar:folder-with-files-linear',
  status: 'solar:check-circle-linear',
  timer: 'solar:clock-circle-linear',
  docs: 'solar:book-bookmark-linear',
  info: 'solar:info-circle-linear',
  link: 'solar:link-linear',
  duplicate: 'solar:copy-linear',
  rotateLeft: 'solar:refresh-square-linear',
  rotateRight: 'solar:restart-linear',
  palette: 'solar:palette-round-linear',
  component: 'solar:sticker-square-linear',
  results: 'solar:sidebar-code-linear',
  steps: 'solar:list-check-linear',
  layersPanel: 'solar:layers-minimalistic-linear',
  pagesPanel: 'solar:notes-linear',
  macros: 'solar:widget-5-linear',
  shortcut: 'solar:keyboard-linear',
  logout: 'solar:logout-2-linear',
  admin: 'solar:shield-user-linear',
  overview: 'solar:pie-chart-2-linear',
};

export function AppIcon({ name, icon, className = '' }) {
  const resolved = icon || APP_ICONS[name] || 'solar:question-circle-linear';
  return <Icon icon={resolved} className={className} aria-hidden="true" />;
}
